import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Blog code.io</title>
      </Head>
      <div className={styles.main}>
        <h1 className={styles.title}>Bienvenue sur Code.io</h1>
        <p className={styles.subTitle}>Le blog communautaire des afficionados de developpement web</p>

        <div className={styles.content}>
          <div className={styles.card}>
            <div className="card-body">
              <h2 className={styles.h2}>Lisez les articles</h2>
              <h6 className="card-subtitle mb-2 text-muted">
                Maximiser votre culture web
              </h6>
              <p className="card-text">
                Chaque auteur tente de vous apporter le plus de valeur possible
                par article.
              </p>
              <Link href="/blog" className="card-link">
                <a>Visitez le blog</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <div className="card-body">
              <h2 className={styles.h2}>Faites un tour vers la liste des membres</h2>
              <h6 className="card-subtitle mb-2 text-muted">
                Faites vous des amis
              </h6>
              <p className="card-text">
                Ajoutez, inviter et discuter avec les différents membres.
              </p>
              <Link href="/liste" className="card-link">
                <a>Découvrez la liste des membres</a>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
